### ISSUE TITLE
Missing dict files

### ISSUE THREAD

**Issue by jjw24** [jjw24/WoxDictionary#5]
![image](https://user-images.githubusercontent.com/26427004/104112670-d5d09e80-5345-11eb-9b86-975824577409.png)

**Comment by jjw24** [comment]
can you give more detail, i dont see the difference in the output files for current and previous version aside from sql entity framework dlls

**Comment by jjw24** [comment]
@taooceros can you give more detail, i dont see the difference in the output files for current and previous version aside from sql entity framework dlls

**Comment by taooceros** [comment]
Well I mean the dictionary plugin require users to download an extra ecdict file, which can be extremely large (300MB to 800MB), which is not included in the release zip. Our current update strategy will delete the original folder and use the new folder with newer version, which means the downloaded ecdict file will be deleted.


Well I actually haven't done the update, but when seeing the code, I assume that's what will happen. If that's true, it means that the downloaded ecdict file will be deleted, which require users to download again every time updating. I assume when updating file, we may also need to copy resources file from older version to the new version. However, I think that's a bit hard because we are hard to know which file is the extra resource file....


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jjw24/WoxDictionary"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月10日(星期天) 上午10:52
收件人:&nbsp;"jjw24/WoxDictionary"<WoxDictionary@noreply.github.com&gt;;
抄送:&nbsp;"天煞"<1569418337@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jjw24/WoxDictionary] Missing dict files (#5)





 
@taooceros can you give more detail, i dont see the difference in the output files for current and previous version aside from sql entity framework dlls

**Comment by jjw24** [comment]
oh ok.

Can that file be stored in the user data folder settings directory instead?

**Comment by taooceros** [comment]
hmmm i believe it could. However, isn't the plugin folder inside the user data folder? Is it good to store data to a parent folder instead of a sub-folder?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jeremy Wu"<notifications@github.com&gt;; 
发送时间: 2021年1月10日(星期天) 中午11:35
收件人: "jjw24/WoxDictionary"<WoxDictionary@noreply.github.com&gt;; 
抄送: "天煞"<1569418337@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [jjw24/WoxDictionary] Missing dict files (#5)





 
oh ok.
 
Can that file be stored in the user data folder settings directory instead?

**Comment by jjw24** [comment]
Yeah I mean the plugin's settings folder inside userdata should store it, just like how a settings file should be stored

**Comment by taooceros** [comment]
Well I am not sure whether plugins are available to the folder Settings.Plugins, since currently Dictionary plugin store its setting inside its plugin folder.









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jeremy Wu"<notifications@github.com&gt;; 
发送时间: 2021年1月10日(星期天) 中午11:57
收件人: "jjw24/WoxDictionary"<WoxDictionary@noreply.github.com&gt;; 
抄送: "天煞"<1569418337@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [jjw24/WoxDictionary] Missing dict files (#5)





 
Yeah I mean the plugin's settings folder inside userdata should store it, just like how a settings file should be stored

**Comment by jjw24** [comment]
transferred to https://github.com/harrynull/Flow.Launcher.Dictionary/issues/2
